insuarance/urls.py
from django.urls import path
from .views import *

app_name = 'insuarance'

urlpatterns = [
    path('add_customer/', add_customer, name='add_customer'),
    path('view_customers/', view_customers, name='view_customers'),
    path('view_customer/<int:customer_id>/', view_customer, name='view_customer'),
    path('add_policy/', add_policy, name='add_policy'),
    path('view_policy/', view_policy, name='view_policy'),
    path('update_policy/', update_policy, name='update_policy'),
    path('add_vehicle/', add_vehicle, name='add_vehicle'),
    path('view_vehicles/', view_vehicles, name='view_vehicles'),
    path('view_vehicle/<str:number_plate>/', view_vehicle, name='view_vehicle'),
    path('dashboard/', dashboard, name='dashboard'),
    path('upload_image/', upload_image, name='upload_image'),


]

vehicle/urls.py
from django.contrib import admin
from django.urls import path, include  # Import the include function

from insuarance.views import add_customer, view_customers, dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('', include('insuarance.urls')),  # Include insuarance URLs for the root path
]

insuarance/models.py
from django.db import models

# Create your models here.
GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)

STATUS_CHOICES = (
    ('Active', 'Active'),
    ('Expired', 'Expired'),
    ('Canceled', 'Canceled'),
)


class Policy(models.Model):
    policy_number = models.CharField(max_length = 50, unique=True)
    start_date = models.DateField()
    end_date = models.DateField()
    premium_amount = models.IntegerField()
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='Active'
    )
    vehicle = models.ForeignKey('Vehicle', on_delete=models.CASCADE, related_name='policies', default=None)

    def __str__(self):
        return f"{self.policy_number}"
class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    dls_no = models.CharField(null=True,max_length=30, unique=True)
    id_number = models.IntegerField(unique=True)
    email = models.EmailField(null=True, unique=True)
    phone_no = models.CharField(default=0,max_length=15)
    address = models.CharField(max_length=30, default='unknown')
    gender = models.CharField(
        max_length=10,
        choices=GENDER_CHOICES,
        default='Male'
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Vehicle(models.Model):
    owner = models.ForeignKey(Customer, on_delete=models.CASCADE)
    model = models.CharField(max_length=30)
    make = models.CharField(max_length=30)
    type = models.CharField(max_length=30)
    number_plate = models.CharField(max_length=20, unique=True)
    color = models.CharField(max_length=30)
    year = models.DateField()
    milleage = models.IntegerField(default=0)
    vehicle_price = models.FloatField(default=0)
    vehicle_policies = models.ManyToManyField(Policy, related_name='vehicles', blank=True)

    def __str__(self):
        return f"{self.number_plate} "

insuarance/forms.py
from django import forms
from django.forms import DateInput

from insuarance.models import Customer, Policy, Vehicle


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = [
            'first_name',
            'last_name',
            'gender',
            'id_number',
            'email',
            'phone_no',
            'dls_no',
            'address',

        ]

class PolicyForm(forms.ModelForm):
    class Meta:
        model = Policy
        fields = [
            'policy_number',
            'start_date',
            'end_date',
            'vehicle',
            'premium_amount',
            'status',
        ]
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date': DateInput(attrs={'type': 'date'}),
        }

    def save(self, commit=True):
        policy = super().save(commit=False)

        # Calculate premium_amount based on date difference
        date_difference = policy.end_date - policy.start_date
        premium_amount = date_difference.days * 100

        # Set the calculated premium_amount
        policy.premium_amount = premium_amount

        if commit:
            policy.save()

        return policy


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = [
            'owner',
            'make',
            'model',
            'type',
            'number_plate',
            'color',
            'year',
            'milleage',
            'vehicle_price',
        ]
        widgets = {
            'year': DateInput(attrs={'type': 'date'})
        }

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

insuarance/views.py
from datetime import timezone
from PIL import Image, ImageEnhance
import pytesseract
from django.db.models import Q
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from insuarance.forms import CustomerForm, PolicyForm, VehicleForm, ImageUploadForm
from insuarance.models import Customer, Policy, Vehicle
from django.contrib import messages



def dashboard(request):
    count_customer = Customer.objects.count()
    count_policies = Policy.objects.count()
    count_vehicle = Vehicle.objects.count()
    context = {
        'count_vehicle':count_vehicle,
        'count_policies':count_policies,
        'count_customer':count_customer,

    }
    return render(request, 'dashboard.html', context)

def add_customer(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            # Saving the form after accessing cleaned_data
            customer = form.save()
            messages.success(request, 'New Customer has been added successfully')
            return redirect('insuarance:view_customers')  # Redirect to the view_customers page
    else:
        form = CustomerForm()

    return render(request, 'add_customer.html', {'form': form})

def view_customers(request):
    customers = Customer.objects.all()
    search_term = request.GET.get('search', '')  # Get search query from GET request
    if search_term:
        customers = Customer.objects.filter(
            Q(first_name__icontains=search_term) |  # Search in name field
            Q(email__icontains=search_term) |  # Search in email field
            Q(last_name__icontains=search_term)
            # Add more fields to search as needed
        )
    else:
        customers = Customer.objects.all()  # Fetch all customers if no search term
    return render(request, 'customer.html', {'customers': customers})
def view_customer(request, customer_id):
    customer = get_object_or_404(Customer, id=customer_id)
    return render(request, 'view_customer.html', {'customer': customer})
def add_policy(request):
    if request.method == 'POST':
        form = PolicyForm(request.POST)
        if form.is_valid():

            policy = form.save()
            messages.success(request,"New policy has been added")
            return redirect('insuarance:view_policy')
    else:
        form = PolicyForm()
    return render(request, 'add_policy.html', {'form': form})
def view_policy(request):
    policies = Policy.objects.all()
    for policy in policies:
        if policy.end_date < timezone.now().date():
            if policy.status =='Active':
                policy.status = 'Expired'
                policy.save()
            # If the end date is past today's date, update the policy status to 'Expired'

    return render(request, 'view_policy.html', {'policies': policies})
def add_vehicle(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST)
        if form.is_valid():
            vehicle = form.save()
            messages.success(request, "Vehicle added successfully")
            return redirect('insuarance:view_vehicles')
    else:
        form = VehicleForm()
    return render(request, 'add_vehicle.html', {'form': form})
def view_vehicles(request):
    vehicles = Vehicle.objects.all()
    return render(request, 'view_vehicles.html', {'vehicles':vehicles})

def view_vehicle(request,number_plate):
    vehicle = get_object_or_404(Vehicle, id=number_plate)


    return render(request, 'view_vehicle.html', {'vehicle': vehicle})
def update_policy(request):
    policies = Policy.objects.all()
    for policy in policies:
        date_difference = policy.end_date - policy.start_date
        policy.date_difference = date_difference.days
        if policy.status == 'Expired' or 'Canceled':
            amount = policy.date_difference * 100
            policy.premium_amount = amount
            policy.status = 'Active'
            policy.save()
    return render(request, 'update_policy.html', {'policies': policies})

#ocr app
def preprocess_image(image_path):
    img = Image.open(image_path)
    img = img.resize((800, 600))  # Resize to an optimal size
    img = img.convert('L')
    return img

def extract_text_from_image(image_path):
    img = preprocess_image(image_path)
    text = pytesseract.image_to_string(img)
    return text.strip()

def search_vehicle_by_number_plate(number_plate):
    try:
        vehicle = Vehicle.objects.get(number_plate=number_plate)

        return vehicle
    except Vehicle.DoesNotExist:
        return None

def handle_uploaded_image(image):
    # Implement the logic to save the uploaded image
    # Example: save it to the 'media' directory
    path = '/home/santos/Pictures/Screenshots' + image.name
    with open(path, 'wb+') as destination:
        for chunk in image.chunks():
            destination.write(chunk)
    return path

def upload_image(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']
            image_path = handle_uploaded_image(image)
            extracted_text = extract_text_from_image(image_path)

            # Search for the vehicle by the extracted text (number plate)
            vehicle = search_vehicle_by_number_plate(extracted_text)

            context = {
                'extracted_text': extracted_text,
                'vehicle': vehicle,
            }
            return render(request, 'ocr_result.html', context)

    else:
        form = ImageUploadForm()

    return render(request, 'upload_image.html', {'form': form})

insuarance/templates/add_customer.html
{% extends 'base.html' %}
{% block content %}
<body>
    <h1>Provide Customer Details</h1>
    <form class="form-group" method="post">
        {% csrf_token %}
        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" required>

        <label for="last_name">Last Name:</label>
        <input type="text" name="last_name" required>

        <label for="email">Email:</label>
        <input type="email" name="email" required>

        <label for="address">Address:</label>
        <input type="text" name="address" required>

        <label for="dls_no">Driving License:</label>
        <input type="text" name="dls_no" required>

        <label for="phone_no">Phone Number:</label>
        <input type="text" name="phone_no" required>

        <label for="id_number">Id Number:</label>
        <input type="text" name="id_number" required>

        <label for="gender">Gender:</label>
        <input type="text" name="gender" required>

        <button type="submit" name="add">Add</button>
    </form>
</body>
{% endblock %}

insuarance/templates/add_policy.html
<!-- policy_form.html -->

{% extends 'base.html' %}

{% block title %}Add Policy{% endblock %}

{% block content %}
  <h2>Add Policy</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
 <script>
        // Function to calculate and update premium amount
        function updatePremiumAmount() {
            const startDate = new Date(document.getElementById('id_start_date').value);
            const endDate = new Date(document.getElementById('id_end_date').value);

            if (!isNaN(startDate) && !isNaN(endDate)) {
                const dateDifference = (endDate - startDate) / (1000 * 60 * 60 * 24);  // Convert milliseconds to days
                const premiumAmount = dateDifference * 100;

                // Update the premium_amount field
                document.getElementById('id_premium_amount').value = premiumAmount.toFixed(2);
            }
        }

        // Add onchange event listeners to start_date and end_date fields
        document.getElementById('id_start_date').addEventListener('change', updatePremiumAmount);
        document.getElementById('id_end_date').addEventListener('change', updatePremiumAmount);
    </script>
{% endblock %}

insuarance/templates/add_vehicle.html
<!-- policy_form.html -->

{% extends 'base.html' %}

{% block title %}Add Vehicle{% endblock %}

{% block content %}
  <h2>Add Vehicle</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

insuarance/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>

            body {
    font-family: copperplate;
    background-color:black;
    margin: 20px;

            align-items: center;
            justify-content: center;

}
h3 {
            color: green;
        }

        #content {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: #007bff;
        }

        form {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        label {
            font-weight: bold;
        }

        button {
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }



.container {
    width: 80%;
    margin: 0 auto;
}

.grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
}

.card {
    background-color: aqua;
    padding: 20px;
    border-radius: 5px;
    text-align: center;
}

.card h2 {
    margin-bottom: 10px;
    font-weight: bold;
    color:black;
    font-size: 150%;
}

.count {
    font-size: 24px;
    font-weight: bold;
    color:black;
}
        .card a{
        color:red;
        font-size: 20px
        }

        //add customer
                body {

        }

        form {
            max-width: 400px;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {

            color: #007bff;
        }

        label {
            display: block;
            margin-top: 10px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-top: 5px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            width: 100%;
            padding: 10px;
            margin-top: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .vehicle-card {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }
 table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #007bff;
            color: #fff;
            font-weight: bold;
        }

        tbody tr:hover {
            background-color: #f5f5f5;
        }
        a {
        color: red;
        }
        .btn-success a{
        color: white;


         h1 {
            color: #007bff;
        }


        p {
            margin: 10px 0;
        }

        strong {
            font-weight: bold;
        }

        .customer-details {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        a {
            display: block;
            margin-top: 20px;
            color: #007bff;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

    </style>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

insuarance/templates/customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer List</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: black;
            margin: 20px;
        }

        .adder {
            margin-top: 20px;
            margin-bottom: 20px;
            text-align: center;
        }

        h1 {
            color: #007bff;
            text-align: center;
        }

        .search {
            text-align: center;
            width:500px;
            margin-left: 28%;

        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Customer List</h1>
        <div class="search">
            <form method="GET">
                <input type="text" name="search" class="form-control" placeholder="Search customers">
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
        <div class="adder">
            <a href="{% url 'insuarance:add_customer'%}" class="btn btn-success">Add Customer</a>
        </div>
        <div class="row">
            {% for customer in customers %}
                <div class="col-md-3">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <a href="{% url 'insuarance:view_customer' customer.id %}" class="card-link">
                                <h5 class="card-title">{{ customer.first_name }} {{ customer.last_name }}</h5>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Bootstrap JS and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

insuarance/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
<body>
    <div class="container">
        <h1>Dashboard</h1>
        <div class="grid">
            <div class="card">
                <h2>Policies</h2>
                <p class="count">{{ count_policies }}</p>
                <a href="{% url 'insuarance:view_policy' %}" class="view-more">View More</a>
            </div>
            <div class="card">
                <h2>Vehicles</h2>
                <p class="count">{{ count_vehicle }}</p>
                <a href="{% url 'insuarance:view_vehicles' %}" class="view-more">View More</a>
            </div>
            <div class="card">
                <h2>Customers</h2>
                <p class="count">{{ count_customer }}</p>
                <a href="{% url 'insuarance:view_customers' %}" class="view-more">View More</a>
            </div>

            <div class="card">
                <a href="{% url 'insuarance:upload_image' %}" class="view-more">Use OCR</a>
            </div>
        </div>

    </div>
</body>
{% endblock %}

insuarance/templates/ocr_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OCR Result</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            color: #007bff;
            text-align: center;
        }

        p {
            margin: 10px 0;
        }

        strong {
            font-weight: bold;
        }

        .result-container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        a {
            display: block;
            margin-top: 20px;
            color: #007bff;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="result-container">
        <h1>OCR Result</h1>
        <p><strong>Extracted Text:</strong> {{ extracted_text }}</p>

        {% if vehicle %}

            <p><strong>Vehicle Owner:</strong> {{ vehicle.owner }}</p>

        {% else %}
            <p><strong>Vehicle Not Found</strong></p>

        {% endif %}
                     {% for policy in vehicle.policies.all %}
        {% if policy.status == 'Active' %}
        <p><strong>Policy:</strong>  {{ policy.policy_number }}</p>
        <p><strong>Status:</strong>  {{ policy.status }}</p>
        <p><strong>From:</strong>  {{ policy.start_date }}</p>
        <p><strong>To:</strong>  {{ policy.end_date }}</p>



        {% endif %}
    <!-- Display other policy details as needed -->
{% endfor %}

        <a href="{% url 'insuarance:upload_image' %}">Upload Another Image</a>
    </div>
</body>
</html>

insuarance/templates/update_policy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Policy Overview</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
            color: #333;
        }

        header {
            background-color: #fff;
            color: #007bff;
            padding: 20px;
            text-align: center;
        }

        h1 {
            margin: 0;
        }
        div {
        height:40px;
        width:150px;
        padding-top:12px;
        margin-top:15px;
        text-align:center;
        background-color:aqua;
        margin-left: 500px
        }


        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #007bff;
            color: #fff;
            font-weight: bold;
        }

        tbody tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>
<body>
    <header>
        <h1>Policy Overview</h1>
    </header>
    <div><a href="{% url 'insuarance:add_policy'%}">Add Policy</a></div>
    <main>
        <table>
            <thead>
                <tr>
                    <th>Policy Number</th>
                    <th>Vehicle</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Premium Amount</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for policy in policies %}
                    <tr>
                        <td>{{ policy.policy_number }}</td>
                        <td>{{ policy.vehicle }}</td>
                        <td>{{ policy.start_date}}</td>
                        <td>{{ policy.end_date }}</td>
                        <td>{{ policy.premium_amount }}</td>
                        <td>{{ policy.status }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
</body>
</html>

insuarance/templates/upload_image.html
<!-- templates/upload_image.html -->
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
<body>
    <h1>Upload Image for OCR</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Submit</button>
    </form>
</body>

{% endblock %}

insuarance/templates/view_customer.html
<!--- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Customer Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 20px;
        }

        h1 {
            color: #007bff;
        }
        h3 {
            color: green;
        }

        p {
            margin: 10px 0;
        }

        strong {
            font-weight: bold;
        }



        a {
            display: block;
            margin-top: 20px;
            color: #007bff;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style> -->
{% extends 'base.html' %}
{% block content %}
</head>
<body>
    <div class="customer-details">
        <center><h1>Customer Details</h1></center>
       <center><p><h3>First Name:</h3> {{ customer.first_name }}</p>
        <p><h3>Last Name:</h3> {{ customer.last_name }}</p>
        <p><h3>ID Number:</h3> {{ customer.id_number }}</p>
        <p><h3>Driving License No.:</h3> {{ customer.dls_no }}</p>
        <p><h3>Address:</h3> {{ customer.address }}</p>
        <p><h3>Email:</h3> {{ customer.email }}</p>
        <p><h3>Phone Number:</h3> {{ customer.phone_no }}</p>
        <p><h3>Gender:</h3> {{ customer.gender }}</p>

        <!-- Add more details as needed -->

        <a href="{% url 'insuarance:view_customers' %}">Back to Customer List</a>
           </center>
    </div>
</body>
</html>
{% endblock %}

insuarance/templates/view_policy.html
<!---<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Policy Overview</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
            color: #333;
        }

        header {
            background-color: #fff;
            color: #007bff;
            padding: 20px;
            text-align: center;
        }

        h1 {
            margin: 0;
        }
        div {
        height:40px;
        width:150px;
        padding-top:12px;
        margin-top:15px;
        text-align:center;
        background-color:aqua;
        margin-left: 500px
        }


        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #007bff;
            color: #fff;
            font-weight: bold;
        }

        tbody tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>
-->
{% extends 'base.html' %}

{% block title %}Add Policy{% endblock %}

{% block content %}
<body>
    <header>
        <h1>Policy Overview</h1>
    </header>
  <center> <div class="btn btn-success"><a href="{% url 'insuarance:add_policy'%}">Add Policy</a></div>
    </center>
      <main>
        <table>
            <thead>
                <tr>
                    <th>Policy Number</th>
                    <th>Vehicle</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Premium Amount</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for policy in policies %}
                    <tr>
                        <td>{{ policy.policy_number }}</td>
                        <td>{{ policy.vehicle }}</td>
                        <td>{{ policy.start_date}}</td>
                        <td>{{ policy.end_date }}</td>
                        <td>{{ policy.premium_amount }}</td>
                        <td>{{ policy.status }}</td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
</body>

{% endblock %}

insuarance/templates/view_vehicles.html
{% extends 'base.html' %}
{% block content %}
<body>
<center><h1>Registered Vehicles</h1></center>
<center><div class="btn btn-success"><a href="{% url 'insuarance:add_vehicle'%}">Add vehicle</a></div></center>
{% for vehicle in vehicles %}
    <div class="vehicle-card">

        <center><h1>{{vehicle.number_plate}} </h1></center>

       <center><p><h3>Owner:</h3> {{ vehicle.owner }}</p>
        <p><h3>Model:</h3> {{ vehicle.model }}</p>
        <p><h3>Make:</h3> {{ vehicle.make }}</p>


        <!-- Add more details as needed -->

        <a href="{% url 'insuarance:view_vehicle' vehicle.id %}">View More</a>
           </center>
    </div>
{% endfor %}
</body>
{% endblock %}